In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
a.shape

(5,)

In [5]:
b = np.arange(6).reshape(2,3)

In [6]:
print(b)

[[0 1 2]
 [3 4 5]]


In [7]:
b = np.array([(23,45,64),(32,45,66)])

In [8]:
print(b)

[[23 45 64]
 [32 45 66]]


In [9]:
b.shape

(2, 3)

In [10]:
c = np.array([6,7,8,9,10])

In [11]:
print(c)

[ 6  7  8  9 10]


In [12]:
d = np.hstack((a,c))

In [13]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
r1 = np.mean(d)
print("Mean: ",r1)

Mean:  5.5


In [15]:
r2 = np.std(d)
print("Standard Deviation: ",r2)

Standard Deviation:  2.8722813232690143


In [16]:
r3 = np.var(d)
print("Variance: ",r3)

Variance:  8.25
